# 参考
# https://docs.github.com/ja/actions/learn-github-actions/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows

# Workflow名
name: Shell Commands
# イベントトリガー
# Git Pushした時にこのワークフローを実行する
on: [push]

jobs:
  # job名(任意の名前で良い)
  Package-to-zip:
    # virtual machineの形式を指定
    runs-on: ubuntu-latest
    # jobのステップ
    steps:
      - uses: actions/checkout@v2
        name: clone this

      - name: ls
        run: ls -al
      # ステップ名
      - name: Package
        run: | 
          zip archive ./*
      - name: Upload release asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
        with:
          uses: shogo82148/actions-upload-release-asset@v1
          with:
          upload_url: ${{github.event.release.upload_url}}
          asset_path: ./archive.zip
          asset_name: Kudoedit.Modded.v4.$(echo "${{github.sha}}" | cut -c 1-8).zip