# 参考
# https://docs.github.com/ja/actions/learn-github-actions/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows

# Workflow名
name: Package into ZIP
# イベントトリガー
# Git Pushした時にこのワークフローを実行する
on: 
  workflow_dispatch:
    

jobs:
  # job名(任意の名前で良い)
  Package-to-zip:
    # virtual machineの形式を指定
    runs-on: ubuntu-latest
    # jobのステップ
    steps:
      - name: mkdir
        run: |
          ls -al
          mkdir output
          cd output

      - uses: actions/checkout@v2
        name: clone this
        with:
          path: output
      # ステップ名
      - name: Minify & Package
        run: | 
          cd output
          rm -rf ./.git
          echo "x=Kudoedit.Modded.v4.$(echo "${{github.sha}}" | cut -c 1-8)" >> $GITHUB_ENV

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.x}}
          path: output/
      
