# 参考
# https://docs.github.com/ja/actions/learn-github-actions/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows

# Workflow名
name: Package into ZIP
# イベントトリガー
# Git Pushした時にこのワークフローを実行する
on: 
  workflow_dispatch:
    

jobs:
  # job名(任意の名前で良い)
  Package-to-zip:
    # virtual machineの形式を指定
    runs-on: ubuntu-latest
    # jobのステップ
    steps:
      - uses: actions/checkout@v2
        name: clone this

      - name: ls
        run: ls -al
      # ステップ名
      - name: Package
        run: | 
          mkdir output
          cd output
          zip -r Kudoedit.Modded.v4.$(echo "${{github.sha}}" | cut -c 1-8) .
          echo "x=Kudoedit.Modded.v4.$(echo "${{github.sha}}" | cut -c 1-8).zip" >> $GITHUB_ENV

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.x}}
          path: output/
      
